### ISSUE TITLE
Divmod wrong quotient on floats

### ISSUE THREAD

**Issue by jussimalinen** [IronLanguages/main#1236]
```python
quotient, remainder = divmod(0.123, 0.001)
quotient * 0.001 + remainder
```
On CPython and Jython the result is correct `0.123`.

On IronPython 2.7.5.0 the result is `0.124`.

More details:

On all above python versions this is true:
```python
(0.123 / 0.001, 0.123 % 0.001) == (123.0, 0.0009999999999999957)
```
But divmod works a bit differently on CPython and Jython:
```python
divmod(0.123, 0.001) == (122.0, 0.0009999999999999957)
```

This is very nice as then using divmod makes sure the `quotient * 0.001 + remainder` results in the original number.

On IronPython divmod however works as if we did the div and mod operations separately and gives us this result:
```python
divmod(0.123, 0.001) == (123.0, 0.0009999999999999957)
```

**Comment by simplicbe** [comment]
That's a little bit curious. If i execute the following line in IronPython (2.7.5.0):

```
quotient, remainder = divmod(0.123, 0.001)
print quotient
print remainder
```

I get the following result:
0.123
0.001

If i execute the same in CPython, i get this result:
0.122
0.001

The problem seems to be here (IntOps.Generated.cs:

```
        [SpecialName]
        public static Double FloorDivide(Double x, Double y) {
            if (y == 0) throw PythonOps.ZeroDivisionError();
            return (Double)Math.Floor(x / y);

        }
```

This is the first value of the created tuple, which returns 123 instead of 122. 

Please correct me if i am totaly wrong.

**Comment by simplicbe** [comment]
@jussimalinen can you provide a fix for this?
