### ISSUE TITLE
PythonGlobals and AST live on

### ISSUE THREAD

**Issue by RamzaGarland360** [IronLanguages/main#1292]
I have an application (external) that calls a new application. This application makes use of the Microsoft ConsoleHost and the IronPython 2.7.5 for C#. The issue is after we exit the IronPython sessions, all appears to close and collect, Runtime is ShutDown, but when running Redgate ANTS, there are thousands of instances of PythonAST's,NameExpressions, and PythonGlobals[]being held in memory. All link towards the globals and PythonContext. Would this possibly be caused by the entire application Not being shut down? By this i mean we exit the secondary application, leaving the external one open, ready to start another 'session' if you will.

**Comment by simplicbe** [comment]
It would help if you clone the newest repository and makes some test using it. Because if this already
solve your problem you can be sure, that the next release (which will come), solves your problem. Just clone `IronLanguages:ipy-2.7-maint` compile the project and try again. In any case this will also help the community.

**Comment by RamzaGarland360** [comment]
Just grabbed latest repo, compiled and transferred the dll's. There seem to be less memory taken per script now, but once the python sessions are "ShutDown", ANTS still shows thousands of instances still in the PythonDictionary, NameExpressions, AST PythonVariable, and tons more. Perhaps its something in how the ShutDown, we call Engine.SetTrace(null), even loop through the Globals calling RemoveVariable, call Terminate(0), manually close all streams (Error, Output and Input), RedirectToConstole, Runtime.Shutdown, PythonContext.BuiltinModuleDict.Clear(), PythonContext.Shutdown, Engine.Runtime.Shutdown, and null everything out. For good measure, i thought i'd abort the thread.... I realize some (or most) of these may be doing the same thing, but all in the end do not clear out the memory used.

**Comment by jdhardy** [comment]
Are you creating your PythonEngine with the "Debug" option? That has some
known leaks. Otherwise, while I've tried to track a bunch of them down, I
wouldn't be surprised if there's still more. The usual culprit is a
PythonContext that gets put in a static variable somewhere inside the
runtime (not directly, but through a chain of objects) causing it to stick
around forever.

If you've got a minimal repro, that would be great. If not, one thing I
assume ANTS can do (JetBrains' dotMemory does) is let you trace back and
find out what is holding onto the PythonContext and PythonGlobals[] - it's
unlikely that they're GC roots, so something must own them and be keeping
them alive.

**Comment by RamzaGarland360** [comment]
We are starting it with the Interactive mode enabled, no Debug option, however we are using tracelines with the main python script that runs everything, which essentially is debug allowing us to exit a python file at any time with some user inputs. We are using the full tree from the repo. The thing about ANTS is, you can traceback so far, however just shows mainly high level of whats holding on to what. There are a few GC roots, but most are not. The tracing for these are so huge. I'll see if i can get down into the code more and see where its all being held. Maybe get a screenshot of it to help.

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#106
