### ISSUE TITLE
Conditional testing for .NET Core / Platform

### ISSUE THREAD

**Issue by slozier** [IronLanguages/main#1366]
The test system needs to be able to skip some tests (e.g. winforms) on .NET Core. The way it skips tests is esentially by looking at the `sys.platform` (e.g. `skiptest("win32")` will skip the test when running on CPython).

The value of `sys.platform` is `cli` for IronPython and `silverlight` for Silverlight. Should we introduce a new platform for .NET Core (e.g. `netstandard` or `cli-netstandard`)?

How do other implementations (e.g. Jython, PyPy) do this type of thing? I'm not exactly sure what the best way to proceed would be...

**Comment by moto-timo** [comment]
I always thought `sys.platform` is `cli` for IronPython was an odd choice. If we mean .NET Core, I kind of like calling it `netcore` or `net-core`. But `cli-netstandard` or `cli-net-core` might be more in keeping with the existing code base. I'm fine with `netstandard` as well. Just my $0.02

**Comment by jdhardy** [comment]
CPython/PyPy set `sys.platform == 'win32'` and `os.name == 'nt'`.

Jython sets `sys.platform == 'win32'` and `os.name == 'java'`.

IronPython sets `sys.platform == 'cli'` and `os.name == 'nt'`.

Python 3 also adds `sys.implementation`.

I'd suggest leaving it as 'cli' and adding a value to the clr module for
the actual underlying implementation (.NET, Mono, .NET Core), version, and
possibly the .NET Standard version that is targeted. It's
IronPython-specific anyway.

(Alternatively: add feature flags such as `clr.features.winforms` or
somesuch so that people aren't checking versions anyway.)

**Comment by moto-timo** [comment]
Thank you for enlightening us, Jeff. This is now ringing a bell because of RobotFramework (tested on multiple flavors of Python), but I obviously forgot.
