### ISSUE TITLE
md5 update SystemError

### ISSUE THREAD

**Issue by ita1024** [IronLanguages/main#1549]
IronPython 2.7.7 RC2 fails on the following:

```python
from hashlib import md5
m = md5()
m.digest()
m.update('foo')
m.digest()
```

The error message mentions:
```
File "testcase" line 4, in <module>
SystemError: Hash not valid for use in specified state
```

CPython 2 and pypy do not raise any exception with the same snippet.

**Comment by slozier** [comment]
While I understand that CPython allows this, can I ask what the use case is for getting a digest before all the data is loaded? The .NET APIs are not at all designed for this type of operation.

Yes it worked with 2.7.5 because that was because all the data was kept in memory (which is terrible if you're trying to get a hash on a large file).

**Comment by slide** [comment]
MD5 wasn't a completely managed implementation, other hashes work. I am importing the managed source from Mono to use internally so it matches the behavior of other hashes.

**Comment by ita1024** [comment]
@slozier intermediate hashes are necessary in this particular case
@slide great
