### ISSUE TITLE
Splash screen

### ISSUE THREAD

**Issue by atulatri** [IronLanguages/main#1581]
Hi,

We created windows executable using ipyc.exe. It takes around a minute or so before GUI screen appears.

Is there any way we can add splash screen in executable?

Thanks & Regards,
Atul Atri.

**Comment by slide** [comment]
There currently isn't support for that right now. It could be added. Have you looked at why it's taking so long?

**Comment by slozier** [comment]
If it's not the exe itself that's slow to load, you could use a 3rd party library to show a splashscreen. For example:
```Python
import clr
clr.AddReference("WindowsBase")
from System.Windows import SplashScreen
from System.IO.Path import GetFullPath

resourceAssembly = clr.LoadAssemblyFromFileWithPath(GetFullPath("ClassLibrary.dll"))
ss = SplashScreen(resourceAssembly, "Resources/Image.png")
ss.Show(True)

raw_input()
```
Note that in this case I referenced ClassLibrary.dll which is an empty library with a single image resource (Resources/Image.png) because the SplashScreen api wants to load the image from an assembly. But you could always find a different one that loads directly from an image file... Or write your own with wpf or forms?

**Comment by atulatri** [comment]
@slide 
I haven't checked yet. Any pointer how should we investigate if it is EXE itself or something else.

@slozier
Thanks for suggestion. I will try it out.

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#67
